language: rust
rust:
  - nightly
services: 
  - postgresql
before_script:
  - psql -c 'create database build_db;' -U postgres
  - echo "DATABASE_URL=postgres://postgres@localhost/build_db" > .env
  - cargo install diesel_cli --no-default-features --features=postgres --force
  - diesel migration run
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
cache: cargo

